google_analytics: UA-180989096-1

# SITE CONFIGURATION
baseurl: ""
url: "https://deveryday.github.io"

# THEME-SPECIFIC CONFIGURATION
title: Dev Every Day                                  # site's title
description: "Algorithm && Dev"      # used by search engines
avatar: assets/img/minelogo.png                         # Empty for no avatar in navbar
favicon: assets/myfavi.ico                            # Icon displayed in the tab

# Header and footer text
header_text: For Better World  # Change Blog header text
header_feature_image: assets/img/KakaoTalk_20201021_130604331.jpg
footer_text: >
  Python Algoritm Click <a href = "https://coreenee.github.io/"> Here </a>

# Blog
excerpt: true                                           # Or "truncate" (first 250 characters), "false" to disable
post_navigation: true
color_image: /assets/img/lineart.png                    # A bit transparent for color posts.

# Features
# More in the _data folder for social icons, share buttons, author and language
# For layout customization, go to the "_sass > base" folder, and check "_variables.scss"
katex: true                                             # Enable if using math markup
mermaid: true                                           # Enable mermaid-js for sequence and diagrams
google_analytics:                                       # Tracking ID, e.g. "UA-000000-01"
cookie_consent: false                                   # To respect the usage of cookies
disqus_shortname:                                       # Your discus shortname for comments

# PAGINATION
paginate: 5
paginate_path: "/blog/page:num"

# PORTFOLIO
collections:
  portfolio:
    output: true
    permalink: /:collection/:name

# BUILD SETTINGS
plugins: [jekyll-paginate, jekyll-seo-tag, jekyll-feed]
exclude: [".jekyll-cache", ".idea", "vendor/*", "assets/node_modules"]

# theme: type-on-strap                                  # if using the theme as a jekyll theme gem
remote_theme: sylhare/Type-on-Strap                     # If using as a remote_theme in github
